# Generated by Django 4.2.2 on 2023-07-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkmaterial",
            name="qty_material",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name="checkmaterial",
            name="stock_qty_material",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
