# Generated by Django 4.2.2 on 2023-07-15 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0002_alter_checkmaterial_qty_material_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckMaterialHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_material", models.DecimalField(decimal_places=2, max_digits=100)),
                ("unit_of_measure", models.CharField(max_length=10)),
                (
                    "stock_qty_material",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                ("last_update_stock_qty", models.DateTimeField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.material",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.plant"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.store"
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
