# Generated by Django 4.2.2 on 2023-07-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_checkmaterialhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkmaterialhistory",
            old_name="user_name",
            new_name="user",
        ),
    ]
